"""
LAC_F04_SIGNUM — Frégate F04
Mission : Finalisation FFmpeg — métadonnées, vérification durée, livrable final
Technologie : FFmpeg (subprocess)
Loi d'isolement : accès à F04/IN/ uniquement
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path


# ─── CONFIGURATION ────────────────────────────────────────────────────────────

TOLERANCE_FRAMES = 2   # Tolérance écart durée vidéo/audio (frames)


# ─── VÉRIFICATION DÉPENDANCES ────────────────────────────────────────────────

def check_dependencies() -> None:
    """Vérifie que ffmpeg et ffprobe sont disponibles dans le PATH."""
    for tool in ("ffmpeg", "ffprobe"):
        if not shutil.which(tool):
            raise RuntimeError(
                f"[SIGNUM] {tool} introuvable dans le PATH. "
                f"Installer avec : apt-get install -y ffmpeg"
            )
    print("[SIGNUM] FFmpeg et ffprobe détectés.")


# ─── INSPECTION VIDÉO ────────────────────────────────────────────────────────

def get_video_duration(path: str) -> float:
    """Retourne la durée d'un fichier vidéo en secondes via ffprobe."""
    cmd = [
        "ffprobe", "-v", "quiet",
        "-print_format", "json",
        "-show_format",
        path
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe échoué : {result.stderr}")
    data = json.loads(result.stdout)
    return float(data["format"]["duration"])


def get_video_info(path: str) -> dict:
    """Retourne les infos complètes d'un fichier via ffprobe."""
    cmd = [
        "ffprobe", "-v", "quiet",
        "-print_format", "json",
        "-show_streams", "-show_format",
        path
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"ffprobe échoué : {result.stderr}")
    return json.loads(result.stdout)


# ─── PIPELINE FFMPEG ──────────────────────────────────────────────────────────

def finalize(
    input_mp4: str,
    timing_json: str,
    output_mp4: str,
    title: str = "LACRIMAE",
    comment: str = "Generated by LACRIMAE — For the Angel's Tears shall become gold.",
) -> bool:
    """
    Finalise le MP4 via FFmpeg :
    - Vérification durée vs timing.json (DURÉE PAR L'AUDIO)
    - Remux propre (stream copy — pas de re-encodage)
    - Injection métadonnées
    - Optimisation moov atom (faststart pour web)
    """
    input_path  = Path(input_mp4)
    output_path = Path(output_mp4)

    # ── Charger le timing ────────────────────────────────────────────────────
    with open(timing_json, "r", encoding="utf-8") as f:
        timing = json.load(f)
    expected_duration = timing["audio_duration_s"]
    fps               = timing.get("fps", 30)

    print(f"[SIGNUM] Durée attendue (timing.json) : {expected_duration:.4f}s")

    # ── Vérifier la durée réelle du MP4 ─────────────────────────────────────
    actual_duration = get_video_duration(str(input_path))
    print(f"[SIGNUM] Durée réelle short_final.mp4 : {actual_duration:.4f}s")

    diff_frames = abs(actual_duration - expected_duration) * fps
    print(f"[SIGNUM] Écart en frames : {diff_frames:.1f} (tolérance : {TOLERANCE_FRAMES})")

    if diff_frames > TOLERANCE_FRAMES:
        print(f"[SIGNUM] AVERTISSEMENT — Écart durée hors tolérance : {diff_frames:.1f} frames")
        # Ne pas bloquer — juste avertir. Remotion peut avoir 1-2 frames de marge.

    # ── Informations source ──────────────────────────────────────────────────
    info = get_video_info(str(input_path))
    video_stream = next((s for s in info["streams"] if s["codec_type"] == "video"), None)
    audio_stream = next((s for s in info["streams"] if s["codec_type"] == "audio"), None)

    if video_stream:
        print(f"[SIGNUM] Vidéo : {video_stream['width']}x{video_stream['height']} "
              f"@ {video_stream.get('r_frame_rate', '?')} — codec {video_stream['codec_name']}")
    if audio_stream:
        print(f"[SIGNUM] Audio : {audio_stream['codec_name']} "
              f"— {audio_stream.get('sample_rate', '?')}Hz")

    # ── Vérification résolution ──────────────────────────────────────────────
    if video_stream:
        w = int(video_stream.get("width", 0))
        h = int(video_stream.get("height", 0))
        if w != 1080 or h != 1920:
            print(f"[SIGNUM] AVERTISSEMENT — Résolution inattendue : {w}x{h} (attendu 1080x1920)")

    # ── FFmpeg — remux + métadonnées + faststart ─────────────────────────────
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "ffmpeg", "-y",
        "-i", str(input_path),
        # Stream copy — pas de re-encodage
        "-c", "copy",
        # Métadonnées
        "-metadata", f"title={title}",
        "-metadata", f"artist=LACRIMAE",
        "-metadata", f"comment={comment}",
        "-metadata", f"year=2026",
        # Optimisation web (moov atom en tête)
        "-movflags", "faststart",
        str(output_path),
    ]

    print(f"\n[SIGNUM] Lancement FFmpeg...")
    # FIX: capture_output=False pour streamer la progression en temps réel dans Colab
    # stderr=subprocess.PIPE uniquement pour récupérer le code d'erreur final
    result = subprocess.run(cmd, capture_output=False)

    if result.returncode != 0:
        print(f"[SIGNUM] ERREUR FFmpeg — code retour : {result.returncode}")
        return False

    # ── Vérification finale ──────────────────────────────────────────────────
    if not output_path.exists():
        print(f"[SIGNUM] ERREUR — short_master.mp4 non créé.")
        return False

    final_size = output_path.stat().st_size
    final_duration = get_video_duration(str(output_path))

    print(f"\n[SIGNUM] short_master.mp4 produit :")
    print(f"  Chemin   : {output_path}")
    print(f"  Taille   : {final_size / 1_000_000:.1f} Mo")
    print(f"  Durée    : {final_duration:.4f}s (attendu {expected_duration:.4f}s)")
    print(f"[SIGNUM] ✓ Mission accomplie.")

    return True


# ─── POINT D'ENTRÉE ───────────────────────────────────────────────────────────

def main():
    # FIX: vérifier ffmpeg/ffprobe disponibles avant de commencer
    check_dependencies()

    base = Path("/content/drive/MyDrive/DRIVE_LACRIMAE")

    input_mp4    = str(base / "F04_SIGNUM" / "IN"  / "short_final.mp4")
    timing_json  = str(base / "F04_SIGNUM" / "IN"  / "timing.json")
    output_mp4   = str(base / "F04_SIGNUM" / "OUT" / "short_master.mp4")

    if len(sys.argv) >= 4:
        input_mp4, timing_json, output_mp4 = sys.argv[1], sys.argv[2], sys.argv[3]

    for p in [input_mp4, timing_json]:
        if not Path(p).exists():
            print(f"[SIGNUM] ERREUR : fichier introuvable → {p}")
            sys.exit(1)

    ok = finalize(input_mp4, timing_json, output_mp4)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
