// Codex de dev — le vrai codex.json est produit par F02_FORMAT et copié dans public/
// Ce fichier sert de fallback (valeurs par défaut du pipeline LACRIMAE dev).
export const codex = {
  version: '3.0',
  pipeline: 'LACRIMAE_DEV',
  video: {
    source: 'clip_001.mp4',
    fps: 30,
    total_frames: 300,
    width: 1080,
    height: 1920,
  },
  text_overlays: [
    {
      id: 'title_00',
      content: 'LACRIMAE',
      start_frame: 0,
      end_frame: 300,
      animation: 'fade_in',
      font: 'Impact, Arial Black, sans-serif',
      size: 96,
      color: '#FFFFFF',
      stroke_color: '#000000',
      stroke_width: 4,
      shadow: '2px 4px 8px rgba(0,0,0,0.9)',
      position: 'top',
      letter_spacing: '0em',
      glow_intensity: 0,
      depth_3d: 0,
    },
  ],
  zoom_keyframes: [],
  logo: {
    src: 'logo.png',
    width_pct: 25,
    position: 'top_left',
    opacity: 1.0,
  },
  brutal_cut_interval_frames: 90,
  volume: 1.0,
  color_preset: 'punchy',
  color_css_filter: 'contrast(1.15) saturate(1.3) brightness(1.05)',
  enhance_4k: false,
  sharpening: 0,
  denoising: 0,
  vignette: 0.25,
  grain_intensity: 0.15,
  slowmo_start_frame: 0,
  slowmo_speed: 1.0,
  shake_power: 0,
  validated_by_magos: false,
};
